#!/bin/sh

export PATH=/usr/pkg/bin:/usr/bin:/bin:/usr/pkg/sbin:/usr/sbin:/sbin
export MANPATH=/usr/pkg/man:/usr/share/man

#compilers

export CC=clang
export CXX=clang++
export FC=flang

#tools

export LD=ld.lld
export AR=llvm-ar
export NM=llvm-nm
export RANLIB=llvm-ranlib
export GREP="ugrep -G"
export EGREP="ugrep -E"
export SED=sed
export PAGER=most


#flags and libraries

export CPPFLAGS=
export COMMON_FLAGS="-flto=thin -march=native -O2 -pipe"
export CFLAGS="$COMMON_FLAGS"
export CXXFLAGS="-stdlib=libc++ $COMMON_FLAGS"
export FFLAGS="$COMMON_FLAGS"
export FCFLAGS="$COMMON_FLAGS"
export FLIBS=
export FCLIBS="$FLIBS"
export LDFLAGS="-fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,-O2 -Wl,--as-needed"
export HOST=x86_64-pc-linux-musl

#compatibility stuff
# netbsd-curses
TERM=vt100
TERMCAP=vt100-w

