#!/bin/mksh

export PATH=/usr/bin:/bin:/usr/sbin:/sbin
export SHELL=/bin/mksh

#compilers

export CC=clang
export CXX=clang++
export FC=flang

#tools

export LD=ld.lld
export AR=llvm-ar
export NM=llvm-nm
export RANLIB=llvm-ranlib
export GREP="ugrep -G"
export EGREP="ugrep -E"
export SED=sed
export PAGER=most


#flags and libraries

export CPPFLAGS=
export COMMON_FLAGS="-flto=thin -march=native -O2 -pipe"
export CFLAGS="$COMMON_FLAGS"
export CXXFLAGS="-stdlib=libc++ $COMMON_FLAGS"
export FFLAGS="$COMMON_FLAGS"
export FCFLAGS="$COMMON_FLAGS"
export FLIBS=
export FCLIBS="$FLIBS"
export LDFLAGS="-fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,-O2 -Wl,--as-needed"
export HOST=x86_64-pc-linux-musl

#compatibility stuff
# netbsd-curses
TERM=vt100
TERMCAP=vt100-w
# ugrep
# alias uq     = '/usr/bin/ug -Q'
# alias ux     = '/usr/bin/ug -UX
# alias uz     = '/usr/bin/ug -z'
# alias grep   = '/usr/bin/ugrep -G'
# alias egrep  = '/usr/bin/ugrep -E'
# alias fgrep  = '/usr/bin/ugrep -F'
# alias pgrep  = '/usr/bin/ugrep -P'
# alias xgrep  = '/usr/bin/ugrep -UX'
# alias zgrep  = '/usr/bin/ugrep -zG'
# alias zegrep = '/usr/bin/ugrep -zE'
# alias zfgrep = '/usr/bin/ugrep -zF'
# alias zpgrep = '/usr/bin/ugrep -zP'
# alias zxgrep = '/usr/bin/ugrep -zUX'
# alias xdump  = '/usr/bin/ugrep -X ""'

