#!/bin/sh

export PATH=/usr/bin:/usr/sbin
export MANPATH=/usr/share/man
export LD_LIBRARY_PATH=/usr/lib

#compilers

export CC=clang
export CXX=clang++
export FC=flang

#tools

export LD=ld.lld
export AR=llvm-ar
export NM=llvm-nm
export RANLIB=llvm-ranlib
export STRIP=llvm-strip
export GREP=grep
export EGREP="ugrep -E"
export FGREP="ugrep -F"
export SED=sed
export PAGER=most

#flags and libraries

export CPPFLAGS=
export COMMON_FLAGS="-flto=thin -march=native -O2 -pipe"
export CFLAGS="$COMMON_FLAGS"
export CXXFLAGS="-stdlib=libc++ $COMMON_FLAGS"
export FFLAGS="$COMMON_FLAGS"
export FCFLAGS="$COMMON_FLAGS"
export FLIBS=
export FCLIBS="$FLIBS"
export LDFLAGS="-fuse-ld=lld -rtlib=compiler-rt -unwindlib=libunwind -Wl,-O2 -Wl,--as-needed"
export HOST=x86_64-pc-linux-musl
export CHOST=$HOST

#security stuff

export SSLBASE=/usr
export SSLCERTS=/etc/openssl/certs
export SSLDIR=/etc/openssl
export SSLKEYS=/etc/openssl/private

# set CVS remote shell command for pkgsrc
export CVSROOT="anoncvs@anoncvs.NetBSD.org:/cvsroot"
CVS_RSH=ssh
export CVS_RSH


#compatibility stuff
# netbsd-curses
TERM=vt100
TERMCAP=vt100-w


